name: Issue Comment Bot

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check for bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: |
          echo "ISSUE_COMMENT=Thank you. We will fix it. Best regards, ${{ github.repository_owner }}." >> $GITHUB_ENV
      
      - name: Check for feature label  
        if: contains(github.event.issue.labels.*.name, 'feature')
        run: |
          echo "ISSUE_COMMENT=Thank you, we will consider to include this feature. Best regards, ${{ github.repository_owner }}." >> $GITHUB_ENV
      
      - name: Check for discussion label
        if: contains(github.event.issue.labels.*.name, 'discussion')
        run: |
          echo "ISSUE_COMMENT=Happy to discuss this topic with you. Best regards, ${{ github.repository_owner }}." >> $GITHUB_ENV
      
      - name: Default comment for unlabeled issues
        if: env.ISSUE_COMMENT == ''
        run: |
          echo "ISSUE_COMMENT=Hello, world!" >> $GITHUB_ENV
      
      - name: Add comment to issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.ISSUE_COMMENT
            })